In [1]:
a = a+1

NameError: name 'a' is not defined

In [2]:
a = 1

In [3]:
a = a + 1

In [3]:
## Script for creating tables

import _mysql

HOST = 'yarn.cueaar94ytrf.us-east-1.rds.amazonaws.com'
PORT = 3306
USER = 'yarn'
PASSWD = 'yarn1234'
DB = 'yarn'

remove_tb = "DROP TABLE IF EXISTS cluster_metrics"

create_tb = """
CREATE TABLE cluster_metrics(
    experiment_id INT,
    time_elapsed BIGINT,
    apps_submitted INT,
    apps_completed INT,
    apps_pending INT,
    apps_running INT,
    apps_failed INT,
    apps_killed INT,
    reserved_mb BIGINT,
    available_mb BIGINT,
    allocated_mb BIGINT,
    total_mb BIGINT,
    reserved_virtual_cores BIGINT,
    available_virtual_cores BIGINT,
    allocated_virtual_cores BIGINT,
    total_virtual_cores BIGINT,
    containers_allocated INT,
    containers_reserved INT,
    containers_pending INT,
    total_nodes INT,
    active_nodes INT,
    lost_nodes INT,
    unhealthy_nodes INT,
    decommisioned_nodes INT,
    rebooted_nodes INT
)
"""
try:
    con = _mysql.connect(host=HOST, port=PORT, user=USER, passwd=PASSWD, db=DB)
    con.query(remove_tb)
    con.query(create_tb)

except _mysql.Error, e:
    print "Error %d: %s" % (e.args[0], e.args[1])
    sys.exit(1)

finally:
    if con:
        con.close()



ImportError: dlopen(/Users/xuhong/anaconda/lib/python2.7/site-packages/_mysql.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/xuhong/anaconda/lib/python2.7/site-packages/_mysql.so
  Reason: image not found

In [6]:
## Script for creating tables

import _mysql
import sys

HOST = 'yarn.cueaar94ytrf.us-east-1.rds.amazonaws.com'
PORT = 3306
USER = 'yarn'
PASSWD = 'yarn1234'
DB = 'yarn'

remove_tb = "DROP TABLE IF EXISTS capacity_scheduler_metrics"

create_tb = """
CREATE TABLE capacity_scheduler_metrics(
    experiment_id INT,
    time_elapsed BIGINT,
    capacity FLOAT,
    used_capacity FLOAT,
    max_capacity FLOAT,
    absolute_capacity FLOAT,
    absolute_max_capacity FLOAT,
    absolute_used_capacity FLOAT,
    num_applications INT,
    queue_name VARCHAR(50),
    state VARCHAR(50),
    resource_used_memory INT,
    resource_used_vcores INT,
    num_active_applications INT,
    num_pending_applications INT,
    num_containers INT,
    max_applications INT,
    max_applications_per_user INT,
    max_active_applications INT,
    max_active_applications_per_user INT
)
"""
try:
    con = _mysql.connect(host=HOST, port=PORT, user=USER, passwd=PASSWD, db=DB)
    con.query(remove_tb)
    con.query(create_tb)

except _mysql.Error, e:
    print "Error %d: %s" % (e.args[0], e.args[1])
    sys.exit(1)

finally:
    if con:
        con.close()


In [1]:
## Script for drawing memory usage

import MySQLdb as mdb
import matplotlib.pyplot as plt

HOST = 'yarn.cueaar94ytrf.us-east-1.rds.amazonaws.com'
PORT = 3306
USER = 'yarn'
PASSWD = 'yarn1234'
DB = 'yarn'

query = "SELECT time_elapsed, allocated_mb from cluster_metrics where experiment_id = 2 order by time_elapsed" 

try:
    con = mdb.connect(host=HOST, port=PORT, user=USER, passwd=PASSWD, db=DB)
    cur = con.cursor()
    cur.execute(query)

    results = cur.fetchall()
    
    time = []
    allocated_mb = []
    
    for result in results:
        time.append(result[0]/1000)
        allocated_mb.append(result[1])
    plt.plot(time, allocated_mb)
    plt.show()
    
except _mysql.Error, e:
    print "Error %d: %s" % (e.args[0], e.args[1])
    sys.exit(1)

finally:
    if con:
        con.close()


In [ ]:
## Script for drawing memory usage

import MySQLdb as mdb
import matplotlib.pyplot as plt

HOST = 'yarn.cueaar94ytrf.us-east-1.rds.amazonaws.com'
PORT = 3306
USER = 'yarn'
PASSWD = 'yarn1234'
DB = 'yarn'

queryA = "SELECT time_elapsed, absolute_used_capacity, queue_name from capacity_scheduler_metrics where experiment_id = 64 order by time_elapsed" 

try:
    con = mdb.connect(host=HOST, port=PORT, user=USER, passwd=PASSWD, db=DB)
    cur = con.cursor()
    cur.execute(queryA)

    results = cur.fetchall()
    
    
    time = []
    memA = []
    memB = []
    
    
    for result in results:
        time.append(result[0]/1000)
        if result[2] == 'realtime':
            memA.append(result[1])
        elif result[2] == 'batch':
            memB.append(result[1])

            
    time = sorted(set(time)) 


    
    max = [10240] * len(time)
    #plt.plot(time, max)


    plt.subplot(2, 1, 1)
    plt.plot(time, memA, 'c')
    plt.subplot(2, 1, 2)
    plt.plot(time, memB, 'c')
    #plt.fill(time, memA, 'b')
    #ax.plot(time, max)
    plt.show()
    
    
    

    
finally:
    if con:
        con.close()


In [14]:
import numpy as np
from matplotlib import pyplot as plt

fnx = lambda : np.random.randint(5, 50, 10)
y = np.row_stack((fnx(), fnx(), fnx()))
x = np.arange(10)

print y
print y1
print fnx()

y1, y2, y3 = fnx(), fnx(), fnx()

fig, ax = plt.subplots()
ax.stackplot(x, y)
plt.show()

fig, ax = plt.subplots()
ax.stackplot(x, y1, y2, y3)
plt.show()

[[31  7 32 28 25 36 33  6 26 46]
 [23 31 21 16 26 25  9 13 37 14]
 [28 20 11  7 40 22 10 32 16  8]]
[29 45  6 12  5 20 26  7 28 32]
[31 16  9  8 19 38 42 49  8 21]
